### ISSUE TITLE
Slack (or custom) profile pictures!

### ISSUE THREAD

**Issue by transcental** [hackclub/hackatime-legacy#11]
It would be great to have profile pictures automatically pulled from Slack or be able to upload a custom one - the leaderboard would look so much nicer

**Comment by taciturnaxolotl** [comment]
a wonderful idea!

**Comment by taciturnaxolotl** [comment]
I think it's time to finally build the slack image bridge I've been procrastinating on

**Comment by taciturnaxolotl** [comment]
Done in https://github.com/hackclub/hackatime/commit/eb052aef583fceb667b2bb5ee20bafe5e51f325f!

![Image](https://github.com/user-attachments/assets/01955eec-cf1f-47a2-9174-7f377a6990a2)

**Comment by taciturnaxolotl** [comment]
it's using https://github.com/taciturnaxolotl/cachet/
