### ISSUE TITLE
How can I create an account at waka.hackclub.com?

### ISSUE THREAD

**Issue by thuanpham582002** [hackclub/hackatime-legacy#13]
@[Kieran Klukas](https://github.com/kcoderhtml)  
Hello, how can I create an account at waka.hackclub.com?  
I saw that the sign-up button at waka.hackclub.com is disabled.  
Or maybe it's because I missed something.  
Thank you.

**Comment by opticaldrive** [comment]
From root page on waka,
> If you are coming from high seas then you need to reset your password before you login. You can reset your password using the forgot password button on the login page :)

You should be able to use the login page to reset your password.
Use your userID or email, you can get your user ID with these instructions:
https://www.workast.com/help/article/how-to-find-a-slack-user-id/

:)

**Comment by thuanpham582002** [comment]
@V205Arduino thank you for your reply.  
My English is not good. I tried to reset the password following the quote on the root page before. But I didn't receive any email from waka.hackclub. 
Maybe I am missing something. I will try again.
Thank you.

**Comment by opticaldrive** [comment]
The email should have been from hackatime@hackclub.com, maybe check spam/junk folders 
:)
