### ISSUE TITLE
Language leaderboard is completely broken.

### ISSUE THREAD

**Issue by Lazylllama** [hackclub/hackatime-legacy#17]
**Describe the bug**
The list seem to be split into parts of 1-10 and just completely broken. See image.
![Image](https://github.com/user-attachments/assets/52399479-cc2a-4f3f-9531-2d80a4725c15)

**Comment by taciturnaxolotl** [comment]
Ah yes; i need to reset the leaderboard

**Comment by taciturnaxolotl** [comment]
should be fixed!
