### ISSUE TITLE
⚠ Heartbeat requests failing

### ISSUE THREAD

**Issue by tmshader** [hackclub/hackatime-legacy#18]
**Describe the bug**
When `wakatime-cli` sends a heartbeat it is met with a `bad request` response from `https://waka.hackclub.com/api/users/current/heartbeats.bulk` which prevents any heartbeats (online or offline) to be counted.

I tested with `vscode-wakatime` and with raw cli commands as well and neither work.

**System information**
Operation system: Windows 10

**Comment by DinosaurPotato534** [comment]
Same issue here, spent some time troubleshooting to no avail.

**Comment by Gitstar-OC** [comment]
@taciturnaxolotl I think reversing todays commit will solve this error ? Should I do that ?

**Comment by DinosaurPotato534** [comment]
@Gitstar-OC Doubt it - Think its a server-side issue. Assuming nothing went wrong, after the server is fixed, anything you did while it was down should have been cached and will be sent.

**Comment by Gitstar-OC** [comment]
Why every issue seems like a server side one when all of the code is there ? @DinosaurPotato534. Server does not automatically makes error and you need to understand that.

**Comment by tmshader** [comment]
I think the culprit is 05c0dd5a1b638dd006447e3f6c82de5379a9a0dd which added back optional values but they are not treated as optional values, so when an extension sends data without those parameters, the request fails.

**Comment by tmshader** [comment]
Closing, as c82f41fc9dda0dd4fd1424935c9b2d370fd11b18 fixed the issue. 🎉
