### ISSUE TITLE
Embeddable badges say wakapi.dev instead of waka.hackclub.com

### ISSUE THREAD

**Issue by zachlatta** [hackclub/hackatime-legacy#7]
When I go to a project page (ex. https://waka.hackclub.com/summary?interval=any&project=loops-to-airtable-analytics), I see a badge for "wakapi.dev" when I expect to see it for "waka.hackclub.com"

![Image](https://github.com/user-attachments/assets/a7b36e17-a54a-4358-832a-4a9e6254408d)

**Comment by opticaldrive** [comment]
Decently sure it’s related to this line of code, the colors match up as well.

https://github.com/hackclub/hackatime/blob/acc01c1c94fdbbec391e4e226517824843ecf778/models/compat/shields/v1/badge.go#L11

**Comment by taciturnaxolotl** [comment]
Fixed in https://github.com/hackclub/hackatime/commit/81a6b01e90b6f65520cc2d832f5336124c1818da

**Comment by taciturnaxolotl** [comment]
> Decently sure it’s related to this line of code, the colors match up as well.

thnks :)
