### ISSUE TITLE
Java is recognised as 2 languages

### ISSUE THREAD

**Issue by KrazyMiner001** [hackclub/hackatime-legacy#9]
**Describe the bug**
Java is recognised as 2 different languages, "Java" and "JAVA". With the same inputs (forwarding through the wakatime integration) wakatime only registers 1 java, combining time of the 2. The bug can be reproduced by coding java in IntelliJ (possibly more ides, have not tested) with the wakatime plugin.

This bug is a problem as the leaderboards only look at one of the java types, making the leaderboards inaccurate.

**Comment by taciturnaxolotl** [comment]
thanks for reporting this! i'm not going to try and fix this as this is more of a plugin problem
